// IMPORT MODULES
import { inter } from '@/fonts';
import '../css/styles.css'
  // These styles apply to every route in the application

// DEFAULT NAMING
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// ROOT LAYOUT
export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  )
}
